// -----------------------------------------------------------------------------------
// Definições:

// Compilação:
// Qual servidor está sendo compilado?
#define         SERVER_ID       			                    1
#define         SERVER_TAG                                      "BNS"
#define         SERVER_NAME                                     "Brasil New Start"
#define			SERVER_NR										"1"
#define			DEFAULT_HOSTNAME								"hostname Brasil New Start | Senha no Discord"
#define			SERVER_YEAR_FOUNDED								"2016"
#define			SERVER_LOGO_URL									"https://i.imgur.com/3sYH8Mh.png"
#define         SERVER_SITE                                     "https://brasilnewstart.com.br"
#define         SERVER_FACEBOOK                                 "https://facebook.com/brasilnewstart"
#define         SERVER_INSTAGRAM                                "https://instagram.com/brasilnewstart"
#define			SERVER_YOUTUBE									"https://youtube.com/@brasilnewstart"
#define			SERVER_TIKTOK									"@brasilnewstart"
#define			SERVER_LINK_RADIO 								"http://stream.zeno.fm/23cw407s2zhvv"

#define			SERVER_EMBED_COLOR 								15105570
#define			SERVER_COLOR_PRIMARY							0xFBD826FF
#define			S_C_PRIMARY							            "FBD826"
#define			SERVER_COLOR_SECONDARY							0xFBD826FF
#define			S_C_SECONDARY							        "FBD826"

#define         SERVER_IP                                       "jogar.brasilnewstart.com.br"
#define			SERVER_PORTA									"7777"

#define			FOUNDER_NAME_01									"Theus_Crazzy"

#define			SERVER_PLAYER_META								40

#define			TEXT_LOGO_HUD									"Brasil~n~New~n~Start"
#define			TEXT_LOGO_HUD_2									"Server ~y~Gold"
#define			TEXT_SERVER_ID									"Server Gold"

// Definições do Discord:
#define         DISCORD_SERVER_ID                               "381623944748466188"
#define         SERVER_DISCORD                                  "https://discord.gg/pj7ySw9tPG"

#define			DISCORD_CHANNEL_BATEPAPO						"382676187023015937"
#define			DISCORD_CHANNEL_SOCIOLOGS						"1175102672366485616"
#define			DISCORD_CHANNEL_COMANDOS						"1212495515921551370"
#define			DISCORD_CHANNEL_CONEXAO							"1212216295844487201"
#define			DISCORD_CHANNEL_ATTENDANCE						"1233884624128708770"
#define			DISCORD_CHANNEL_ADMINAVISO						"1235065975637016691"

#define         VIP_FREE_ACTIVE                                 true
#define			SERVER_PASCOA				                    false
#define         C_ARRAIA                                        "{FF0000}"
#define			SERVER_ARRAIA				                    false

// Cores: (Styles)
#include <colors>

// Informa qual mês a GameMode irá funcionar (metodo de proteção)
#define			MES_ACESSED_GAMEMODE 							12	// Dezembro

// Informa a hora do GMX automática
#define			HORA_GMX_AUTOMATICO								9	// 9hr da manhã

// Quantidade de dias que o ano tem:
#define			DAYS_OF_YEAR									366

// IP do TeamSpeak3:
#define			SERVER_TEAMSPEAK3								"SEM TEAMSPEAK"

// Language (opção que aparece na lista do SA-MP)
#define         SERVER_LANGUAGE     			                "Português | Brasil"

// Senha caso o servidor estiver de manutenção
#define			SERVER_PASSWORD									"manu"

// Nome do BOT do servidor
#define			SERVER_BOT_NAME									"BOT Ryder"

// Sexo:
#define			MASCULINO										1
#define			FEMININO										2

// -----------------------------------------------------------------------------------
// Teclas (definições):

// Tecla a ser pressionada para entrar em interiores (usado em 3dTexts)
#define			_KEY_PATH_ENTER_INT_COLOR						"'Y'"

// Tecla a ser pressionada para uso em outros sistemas (usado em 3dTexts)
#define			_KEY_PATH_USE_HORN_COLOR						"'H'"

// -----------------------------------------------------------------------------------
// Atalhos:

#define 		or												||          // Separador || e && nas if/else