

// ------------------------------------------------------------------------------------------------------------------
// Esse valor é definido para limite na mão ao spawnar
#define         max_money_limit             (999999999)

// Órgãos vendidos no Mercado Negro:
#define			PRICE_ORGAO_CABECA          50000         // + Preço de vender cabeça no mercado negro (Sequestro)
#define			PRICE_ORGAO_TRONCO          75000         // + Preço de vender tronco no mercado negro (Sequestro)
#define			PRICE_ORGAO_PERNA           45000        // + Preço de vender perna no mercado negro (Sequestro)
#define			PRICE_ORGAO_BRACO           40000         // + Preço de vender braço no mercado negro (Sequestro)

// Bebidas do /beber
#define			PRICE_BEBER_CERVEJA         80 		        // - Preço de beber cerveja (/beber)
#define         PRICE_BEBER_VODKA           150				// - Preço de beber vodka (/beber)
#define         PRICE_BEBER_WHISKY          250              // - Preço de beber whisky (/beber)
#define         PRICE_BEBER_COCA            60              // - Preço de beber coca-cola (/beber)
#define         PRICE_BEBER_AGUA            50               // - Preço de beber água (/beber)

// Valor para enviar um SMS
#define         PRICE_ENVIAR_SMS            10				// - Preço ao enviar um (/sms)

// Bônus sócio
#define         PRICE_UP_SOCIOCOMUM         5000         // + Preço ganha ao ativar sócio comum (/menu)
#define         PRICE_UP_SOCIOPREMIUM       9000         // + Preço ganha ao ativar sócio power (/menu)
#define         PRICE_UP_SOCIOSUPREME       13000         // + Preço ganha ao ativar sócio supreme (/menu)
#define         PRICE_UP_SOCIOEXTREME       20000        // + Preço ganha ao ativar sócio extreme (/menu)

// Registro
#define         PRICE_INICIO_NOVATO         10000          // + Preço ganha ao criar conta no servidor

// Pátio da PRF valor para retirada
#define         PRICE_VEHICLE_PATIO         10000            // - Preço para retirar veículo do pátio