#define MAX_CATEGORY_BURGUERSHOT 6
#define MAX_ITENS_BURGUERSHOT 21

new const BurguerShot_Category[MAX_CATEGORY_AMMUNATION][enumMenuCategory] = 
{
    { 1, "Armas branca", 8, 0 },
    { 2, "Pistolas", 3, 8 },
    { 3, "Dozes", 3, 11 },
    { 4, "Submetralhadoras", 3, 14 },
    { 5, "Fuzis", 2, 16 },
    { 6, "Rifles", 2, 18 }
};

new const BurguerShot_Item[MAX_ITENS_AMMUNATION][enumMenuItem] = 
{
    { 1, 800, "WEAPONS", "SHP_TRAY_IN" },
    { 2, 1100, "WEAPONS", "SHP_TRAY_IN" },
    { 4, 1500, "WEAPONS", "SHP_TRAY_IN" },
    { 5, 1000, "WEAPONS", "SHP_TRAY_IN" },
    { 6, 1100, "WEAPONS", "SHP_TRAY_IN" },
    { 7, 1100, "WEAPONS", "SHP_TRAY_IN" },
    { 8, 3500, "WEAPONS", "SHP_TRAY_IN" },
    { 15, 3000, "WEAPONS", "SHP_TRAY_IN" },
    { 22, 100, "WEAPONS", "SHP_TRAY_IN" },
    { 23, 200, "WEAPONS", "SHP_TRAY_IN" },
    { 24, 300, "WEAPONS", "SHP_TRAY_IN" },
    { 25, 600, "WEAPONS", "SHP_TRAY_IN" },
    { 26, 700, "WEAPONS", "SHP_TRAY_IN" },
    { 27, 1200, "WEAPONS", "SHP_TRAY_IN" },
    { 28, 900, "WEAPONS", "SHP_TRAY_IN" },
    { 29, 500, "WEAPONS", "SHP_TRAY_IN" },
    { 32, 800, "WEAPONS", "SHP_TRAY_IN" },
    { 30, 1800, "WEAPONS", "SHP_TRAY_IN" },
    { 31, 2000, "WEAPONS", "SHP_TRAY_IN" },
    { 33, 1500, "WEAPONS", "SHP_TRAY_IN" },
    { 34, 3000, "WEAPONS", "SHP_TRAY_IN" }
};