// Branco
#define         COLOR_WHITE             0xFFFFFFFF
#define         C_WHITE                 "{FFFFFF}"

#define         COLOR_LIGHTWHITE        0xF5F4F4FF
#define         C_LIGHTWHITE            "{F5F4F4}"

// Vermelho
#define         COLOR_RED               0xFF0000FF
#define         C_RED                   "{FF0000}"

// Verde
#define         COLOR_GREEN             0x00FF00FF
#define         C_GREEN                 "{00FF00}"

// Amarelo
#define         COLOR_YELLOW			0xFFF000FF
#define         C_YELLOW                "{FFF000}"

// Amarelo Queimado
#define         COLOR_BURNED_YELLOW     0xF5DEB3FF
#define         C_BURNED_YELLOW         "{F5DEB3}"

// Cian
#define         COLOR_CYAN              0x5BEFFDFF
#define         C_CYAN                  "{5BEFFD}"

// Cian
#define         COLOR_CASH              0x5BEFFDFF
#define         C_CASH                  "{5BEFFD}"

// Cinza
#define         COLOR_GRAY              0xA4A5A5FF
#define         C_GRAY                  "{A4A5A5}"

// Cinza
#define         COLOR_GRAY2             0x616161FF
#define         C_GRAY2                 "{616161}"

// Marrom
#define         COLOR_BROWN             0x824D03FF
#define         C_BROWN                 "{824D03}"

// Vermelho light
#define         COLOR_LIGHTRED          0xFA4747FF
#define         C_LIGHTRED              "{FA4747}"

// Green light
#define         COLOR_LIGHTGREEN        0x9ACD32AA
#define         C_LIGHTGREEN            "{9ACD32}"

#define         COLOR_ALERT             0xF31C1CFF          // Alert color
#define         C_ALERT                 "{F31C1C}"          // Alert color

#define         COLOR_SAMP              0xACCBF1FF          // Default color samp
#define         C_SAMP                  "{ACCBF1}"          // Default color samp

#define         COLOR_OPENMP            0x9083D2FF          // Default color open.mp
#define         C_OPENMP                "{9083D2}"          // Default color open.mp

// Cor laranja do SA-MP
#define         COLOR_SAMP_ORANGE       0xF07B0FFF
#define         C_SAMP_ORANGE           "{F07B0F}"

// Cor do fundo preto fosco
#define         COLOR_BACKGROUND        0x151515FF
#define         C_BACKGROUND            "{151515}" // Secondary: 06060690

// Pessego
#define         COLOR_NOTIFICATION      0x18AAFAFF
#define         C_NOTIFICATION          "{18AAFA}"

// Cinza escuro
#define         COLOR_WARNING           0x676868FF
#define         C_WARNING               "{676868}"

// Cor de dinheiro
#define         COLOR_MONEY             0x1A9414FF
#define         C_MONEY                 "{1A9414}"

// Pessego
#define         COLOR_PEACH             0xFC6A6AFF
#define         C_PEACH                 "{FC6A6A}"

// Azul light
#define         COLOR_LIGHTBLUE         0x33CCFFAA
#define         C_LIGHTBLUE             "{33CCFF}"

// Night blue
#define         COLOR_NIGHTBLUE         0x4578FAFF
#define         C_NIGHTBLUE             "{4578FA}"

// Cor laranja:
#define         COLOR_ORANGE            0xFFA500FF
#define         C_ORANGE                "{FFA500}"

// Cinza claro
#define         C_GREY                  "{AFAFAF}"

// Color bluelight
#define         C_BLUELIGHT             "{88D8BE}"
#define         COLOR_BLUELIGHT         0x88D8BEFF

// 
#define         C_BLUEGOD               "{0091FF}"
#define         COLOR_BLUEGOD           0x0091FFFF


// Cor da Equipe de Desenvolvimento
#define         C_DES                   "{00BFFF}"
#define         COLOR_DES               0x00BFFFFF

// Cores de informações para desenvolvedores
#define         COLOR_DEV               0x2B6897AA
#define         C_DEV                   "{2B6897}"

#define         COLOR_SOA               0x576176AA
#define         C_SOA                   "{576176}"

#define         COLOR_WARLOCKS          0xA3283DAA
#define         C_WARLOCKS              "{A3283D}"

#define         COLOR_POLICIA_CIVIL     0x996600AA
#define         C_POLICIA_CIVIL         "{996600}"

#define         TEAM_BALLAS_COLOR       0x9900FFAA
#define         C_TEAM_BALLAS           "9900FF"

#define         COLOR_CHAT_STAFF        0x578FE9FF

#define         COLOR_CHAT_GESTAO       0xC4437BFF

#define         COLOR_SELECTED          0x161616FF

#define         COLOR_VIP               0xF5C62FFF

#define         COLOR_ERROR             0xFC482CFF
#define         COR_ACAOCHAT            0x66CDAAFF
#define         COR_AZTECAS             0x0049C8AA     // ORG: ADA [5]
#define         COLOR_RUSSA             0xD85300AA     // ORG: Máfia Italiana [12]
#define         COLOR_YAK               0x00483AAA
#define         COLOR_RIFA              0xF09F50AA
#define         COLOR_BAIRRO13          0x1C1C1CAA      // Org 18
#define         COLOR_CV                0x840410AA     // ORG: C.V [19]   Cor antiga: 0xF09F50AA
#define         COR_CVSF                0x690000AA     // ORG Antiga inexistente dos Bloods (ORG: 19)
#define         COR_PCC                 0x7F994CAA
#define         COR_COSANOSTRA          0x33FFFFAA
#define         TEAM_CYAN_COLOR         0xA92BF6F6
#define         COLOR_PURPLE            0xC2A2DAAA
#define         TEAM_GROVE_COLOR        0x00D900AA
#define         TEAM_AZTECAS_COLOR      0x2641FEAA
#define         COLOR_GRAD              0xB4B5B7FF
#define         COLOR_DBLUE             0x2641FEAA
#define         COLOR_GREY              0xAFAFAFAA
#define         COLOR_FADE1             0xE6E6E6E6
#define         COLOR_FADE2             0xC8C8C8C8
#define         COLOR_FADE3             0xAAAAAAAA
#define         COLOR_FADE4             0x8C8C8C8C
#define         COLOR_FADE5             0x6E6E6E6E
#define         TEAM_HIT_COLOR          0xFFFFFF00
#define         TEAM_BLUE_COLOR         0x8D8DFF00




// #define embed_default    (0)
// #define embed_green     (5763719)
// #define embed_blue    (3447003)
// #define embed_purple     (10181046)
// #define embed_gold     (15844367)
// #define embed_red     (15548997)
// #define embed_orange     (15105570)
// #define embed_grey    (9807270)
// #define embed_yellow    (16776960)