#if defined _inc_body
	#endinput
#endif
#define _inc_body true

#include <skins_attachments_fixed>

#define		SLOT_HAND_RIGHT		4		// Mão direita

#define Slot_Pizza          1
#define Slot_Mochila        1
#define Slot_Explosivo      2
#define Slot_Maconha        2
#define Slot_Movel          2
#define Slot_Colete         3
#define Slot_Capacete       4

#define Slot_Guitarra       5
#define Slot_Oculos         6
#define Slot_Relogio        7
#define Slot_Bone       	8
#define Slot_Bandana        9

new const _death_bodyparts_name[11][25] = {
	"Desconhecida",
	"Espancamento",
	"Desconhecida",
	"Tiro no Peito",
	"Tiro na Virilha",
	"Tiro no Braço Esquerdo",
	"Tiro no Braço Direito",
	"Tiro na Perna Esquerda",
	"Tiro na Perna Direita",
	"Tiro na Cabeça",
	"Esfaqueamento"
};